import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'pc-language'

const translations = {
  en: {
    nav: {
      home: 'Home',
      pedestalCalculator: 'Pedestal Calculator',
      myProjects: 'My Projects',
    },
    header: {
      toggleSidebar: 'Toggle sidebar',
      toggleTheme: 'Toggle theme',
      light: 'Light',
      dark: 'Dark',
      auto: 'Auto',
      language: 'Language',
      english: 'English',
      chinese: 'Chinese',
      collapse: 'Collapse',
      signOut: 'Sign Out',
    },
    auth: {
      shellSubtitle: 'Deck takeoffs, pedestal schedules, and quote-ready layouts.',
      shellQuote: 'Built for fast rooftop layout review without losing the project history.',
      shellWorkspace: 'ENMON project workspace',
      savedProjects: 'Saved projects',
      aiPlanImport: 'AI plan import',
      pdfQuotes: 'PDF quotes',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      continueAsGuest: 'Continue as Guest',
      signInSubtitle: 'Open saved layouts, AI imports, and quote history.',
      createAccount: 'Create Account',
      creatingAccount: 'Creating account...',
      createAccountSubtitle: 'Save project revisions and return to quotes later.',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      needAccount: 'Need an account?',
      createOne: 'Create one',
      alreadyRegistered: 'Already registered?',
      signInLink: 'Sign in',
      envMissing: 'Add `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY` to your env file.',
      enterEmailPassword: 'Enter your email and password.',
      enterAccountPassword: 'Enter an email and password.',
      passwordsMismatch: 'Passwords do not match.',
      accountCreated: 'Account created. Please check your email to confirm your account.',
    },
    common: {
      loading: 'Loading...',
      save: 'Save',
      saveAs: 'Save As',
      cancel: 'Cancel',
      help: 'Help',
      new: 'New',
      edit: 'Edit',
      delete: 'Delete',
      load: 'Load',
      reload: 'Reload',
      previous: 'Previous',
      next: 'Next',
      gotIt: 'Got it',
      projectName: 'Project name',
      active: 'Active',
      draft: 'Draft',
      saved: 'Saved',
      localDraft: 'Local draft',
      yes: 'Yes',
      no: 'No',
    },
    projects: {
      untitled: 'Untitled Project',
      project: 'Project',
      actions: 'Actions',
      overview: 'Overview',
      shapes: 'Shapes',
      vertices: 'Vertices',
      area: 'Area',
      perimeter: 'Perimeter',
      savedProjects: 'Saved Projects',
      renameProject: 'Rename project',
      saveThisProject: 'Save this project to see it here.',
      loadingProjects: 'Loading projects...',
      myProjects: 'My Projects',
      noSavedProjectsYet: 'No saved projects yet',
      savedProjectCount_one: '1 saved project',
      savedProjectCount_other: '{count} saved projects',
      supabaseMissing: 'Supabase is not configured. Add `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY` to enable project saving.',
      noSavedProjects: 'No saved projects',
      saveAProject: 'Save a project from the calculator to see it here.',
      goToCalculator: 'Go to Calculator',
      lastUpdated: 'Last updated: {value}',
      created: 'Created: {value}',
      deleteConfirm: 'Delete "{name}"? This cannot be undone.',
      deletedNotice: 'Deleted "{name}".',
      savedNotice: 'Saved "{name}".',
      loadedNotice: 'Loaded "{name}".',
      enterProjectName: 'Enter a project name.',
      saveProject: 'Save Project',
      saveProjectAs: 'Save Project As',
      grid: 'Grid',
    },
    calculator: {
      brand: 'Pedestal Calc',
      aiImport: 'AI Import',
      outline: 'Outline',
      tiles: 'Tiles',
      heights: 'Heights',
      quote: 'Quote',
      stepOutlineTitle: 'Outline',
      stepOutlineContent: 'Draw your desired layout on the grid. Click and drag to create shapes. You can create multiple shapes to represent different areas of your space. Use the grid size controls to adjust the scale of your design.',
      stepTilesTitle: 'Tile Layout',
      stepTilesContent: "In this step, you'll see how tiles will be arranged in your design. The system will automatically calculate the optimal tile placement based on your design. You can adjust tile sizes and patterns here.",
      stepHeightsTitle: 'Pedestal Heights',
      stepHeightsContent: 'Set the height for each pedestal in your design. This is crucial for proper drainage and leveling. You can adjust heights individually or use the bulk adjustment tools for efficiency.',
      stepQuoteTitle: 'Quote',
      stepQuoteContent: "Review your complete design specifications and get a detailed quote. You'll see a breakdown of materials, quantities, and costs. You can make final adjustments before proceeding.",
      supabaseMissing: 'Supabase is not configured yet. Add `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY` to your env file to enable auth and project persistence.',
      printInvoice: 'Print Invoice',
      pedestals: 'Pedestals',
      avgHeight: 'Avg Height',
      units: 'Units',
      canvas: 'Canvas',
      shapesPanel: 'Shapes',
      referenceImage: 'Reference Image',
      shortcuts: 'Shortcuts',
      imperial: 'Imperial',
      metric: 'Metric',
      undo: 'Undo',
      redo: 'Redo',
      region_one: '1 region',
      region_other: '{count} regions',
      newShape: 'New Shape',
      points: '{count} points',
      closed: 'closed',
      open: 'open',
      rename: 'Rename',
      uploadImage: 'Upload Image',
      opacity: 'Opacity',
      replace: 'Replace',
      remove: 'Remove',
      shortcutPanCanvas: 'pan canvas',
      shortcutUndoPoint: 'undo point',
      shortcutRedoPoint: 'redo point',
      shortcutPauseCancel: 'pause or cancel edit',
      shortcutCornerEdge: 'corner and edge options',
      stepInstructions: 'Step Instructions',
      setPointHeight: 'Set Point Height',
      height: 'Height',
      confirm: 'Confirm',
      setLineLength: 'Set Line Length',
      length: 'Length',
      invalidPositiveLength: 'Please enter a valid positive number for length.',
      tileSize: 'Tile Size',
      orientation: 'Orientation',
      landscape: 'Landscape',
      portrait: 'Portrait',
      pattern: 'Pattern',
      stacked: 'Stacked',
      calculatedPedestals: 'Calculated pedestals',
      visible: 'Visible',
      hidden: 'Hidden',
      pedestalHeightsTitle: 'Pedestal Heights',
      pedestalHeightsHelp: 'Click a pedestal to edit one height. Hold Shift and drag to set multiple pedestals.',
      data: 'Data',
      clearSavedHeights: 'Clear Saved Heights',
      zoomIn: 'Zoom In',
      zoomOut: 'Zoom Out',
      computingHeights: 'Computing heights…',
      invalidHeight: 'Invalid height entered. Please enter a number.',
      summary: 'Summary',
      pedestalCategory: 'Pedestal Category',
      skuBreakdown: 'SKU Breakdown',
      notes: 'Notes',
      layoutPlan: 'Layout Plan',
      noPedestalData: 'No pedestal data yet',
      addProjectNotes: 'Add project notes (printed on quote)...',
      materialQuote: 'Material Quote',
      reference: 'Ref',
      preparedFor: 'Prepared For',
      category: 'Category',
      date: 'Date',
      skus: 'SKUs',
      noLayoutData: 'No layout data',
      pedestalSchedule: 'Pedestal Schedule',
      rangeMm: 'Range mm',
      qty: 'Qty',
      total: 'Total',
      projectNotes: 'Project Notes',
      disclaimerLabel: 'Disclaimer',
      disclaimerText: 'Quantities are based on computed pedestal heights. Heights outside defined SKU ranges are listed as Unmatched. Verify site conditions before placing any order.',
      generatedBy: 'Generated by ENMON Pedestal Calculator',
      tiles600: 'Tiles (600×600)',
      pedestalsOutdoorFlooring: 'pedestals & outdoor flooring',
      unmatched: 'Unmatched',
    },
  },
  zh: {
    nav: {
      home: '首页',
      pedestalCalculator: '支座计算器',
      myProjects: '我的项目',
    },
    header: {
      toggleSidebar: '切换侧边栏',
      toggleTheme: '切换主题',
      light: '浅色',
      dark: '深色',
      auto: '自动',
      language: '语言',
      english: '英文',
      chinese: '中文',
      collapse: '收起',
      signOut: '退出登录',
    },
    auth: {
      shellSubtitle: '露台放样、支座排布和可直接报价的布局方案。',
      shellQuote: '专为快速屋顶布局审核而设计，同时保留完整项目历史。',
      shellWorkspace: 'ENMON 项目工作区',
      savedProjects: '已保存项目',
      aiPlanImport: 'AI 图纸导入',
      pdfQuotes: 'PDF 报价单',
      signIn: '登录',
      signingIn: '登录中...',
      continueAsGuest: '以访客身份继续',
      signInSubtitle: '打开已保存布局、AI 导入结果和报价历史。',
      createAccount: '创建账户',
      creatingAccount: '正在创建账户...',
      createAccountSubtitle: '保存项目版本，稍后继续报价。',
      email: '邮箱',
      password: '密码',
      confirmPassword: '确认密码',
      needAccount: '还没有账户？',
      createOne: '创建账户',
      alreadyRegistered: '已经注册？',
      signInLink: '登录',
      envMissing: '请在环境文件中添加 `VITE_SUPABASE_URL` 和 `VITE_SUPABASE_ANON_KEY`。',
      enterEmailPassword: '请输入邮箱和密码。',
      enterAccountPassword: '请输入邮箱和密码。',
      passwordsMismatch: '两次输入的密码不一致。',
      accountCreated: '账户已创建。请查收邮件以确认您的账户。',
    },
    common: {
      loading: '加载中...',
      save: '保存',
      saveAs: '另存为',
      cancel: '取消',
      help: '帮助',
      new: '新建',
      edit: '编辑',
      delete: '删除',
      load: '加载',
      reload: '重新加载',
      previous: '上一步',
      next: '下一步',
      gotIt: '知道了',
      projectName: '项目名称',
      active: '当前',
      draft: '草稿',
      saved: '已保存',
      localDraft: '本地草稿',
      yes: '是',
      no: '否',
    },
    projects: {
      untitled: '未命名项目',
      project: '项目',
      actions: '操作',
      overview: '概览',
      shapes: '形状',
      vertices: '顶点',
      area: '面积',
      perimeter: '周长',
      savedProjects: '已保存项目',
      renameProject: '重命名项目',
      saveThisProject: '保存此项目后会显示在这里。',
      loadingProjects: '正在加载项目...',
      myProjects: '我的项目',
      noSavedProjectsYet: '还没有已保存项目',
      savedProjectCount_one: '1 个已保存项目',
      savedProjectCount_other: '{count} 个已保存项目',
      supabaseMissing: 'Supabase 尚未配置。请添加 `VITE_SUPABASE_URL` 和 `VITE_SUPABASE_ANON_KEY` 以启用项目保存。',
      noSavedProjects: '没有已保存项目',
      saveAProject: '从计算器中保存项目后会显示在这里。',
      goToCalculator: '前往计算器',
      lastUpdated: '最后更新：{value}',
      created: '创建时间：{value}',
      deleteConfirm: '删除“{name}”？此操作无法撤销。',
      deletedNotice: '已删除“{name}”。',
      savedNotice: '已保存“{name}”。',
      loadedNotice: '已加载“{name}”。',
      enterProjectName: '请输入项目名称。',
      saveProject: '保存项目',
      saveProjectAs: '项目另存为',
      grid: '网格',
    },
    calculator: {
      brand: '支座计算器',
      aiImport: 'AI 导入',
      outline: '轮廓',
      tiles: '铺砖',
      heights: '高度',
      quote: '报价',
      stepOutlineTitle: '轮廓',
      stepOutlineContent: '在网格上绘制所需布局。点击并拖动即可创建形状。你可以创建多个形状来表示空间中的不同区域。使用网格尺寸控件调整设计比例。',
      stepTilesTitle: '铺砖布局',
      stepTilesContent: '此步骤会显示瓷砖在设计中的排列方式。系统会根据你的设计自动计算最佳铺砖布局。你也可以在这里调整瓷砖尺寸和铺设方式。',
      stepHeightsTitle: '支座高度',
      stepHeightsContent: '为设计中的每个支座设置高度。这对排水和找平非常关键。你可以逐个调整高度，也可以使用批量调整工具提高效率。',
      stepQuoteTitle: '报价',
      stepQuoteContent: '查看完整设计规格并获取详细报价。你将看到材料、数量和成本的明细，并可在继续前进行最终调整。',
      supabaseMissing: 'Supabase 尚未配置。请在环境文件中添加 `VITE_SUPABASE_URL` 和 `VITE_SUPABASE_ANON_KEY` 以启用登录和项目持久化。',
      printInvoice: '打印报价单',
      pedestals: '支座',
      avgHeight: '平均高度',
      units: '单位',
      canvas: '画布',
      shapesPanel: '形状',
      referenceImage: '参考图片',
      shortcuts: '快捷键',
      imperial: '英制',
      metric: '公制',
      undo: '撤销',
      redo: '重做',
      region_one: '1 个区域',
      region_other: '{count} 个区域',
      newShape: '新建形状',
      points: '{count} 个点',
      closed: '已闭合',
      open: '未闭合',
      rename: '重命名',
      uploadImage: '上传图片',
      opacity: '透明度',
      replace: '替换',
      remove: '移除',
      shortcutPanCanvas: '平移画布',
      shortcutUndoPoint: '撤销点位',
      shortcutRedoPoint: '重做点位',
      shortcutPauseCancel: '暂停或取消编辑',
      shortcutCornerEdge: '顶点和边选项',
      stepInstructions: '步骤说明',
      setPointHeight: '设置点高度',
      height: '高度',
      confirm: '确认',
      setLineLength: '设置线段长度',
      length: '长度',
      invalidPositiveLength: '请输入有效的正数长度。',
      tileSize: '瓷砖尺寸',
      orientation: '方向',
      landscape: '横向',
      portrait: '纵向',
      pattern: '铺设方式',
      stacked: '直铺',
      calculatedPedestals: '计算支座',
      visible: '显示',
      hidden: '隐藏',
      pedestalHeightsTitle: '支座高度',
      pedestalHeightsHelp: '点击单个支座可编辑高度。按住 Shift 并拖动可一次设置多个支座。',
      data: '数据',
      clearSavedHeights: '清除已保存高度',
      zoomIn: '放大',
      zoomOut: '缩小',
      computingHeights: '正在计算高度…',
      invalidHeight: '输入的高度无效。请输入数字。',
      summary: '汇总',
      pedestalCategory: '支座类别',
      skuBreakdown: 'SKU 明细',
      notes: '备注',
      layoutPlan: '布局图',
      noPedestalData: '暂无支座数据',
      addProjectNotes: '添加项目备注（将打印在报价单上）...',
      materialQuote: '材料报价单',
      reference: '编号',
      preparedFor: '客户',
      category: '类别',
      date: '日期',
      skus: 'SKU 数量',
      noLayoutData: '没有布局数据',
      pedestalSchedule: '支座清单',
      rangeMm: '范围 mm',
      qty: '数量',
      total: '合计',
      projectNotes: '项目备注',
      disclaimerLabel: '免责声明',
      disclaimerText: '数量基于计算得出的支座高度。超出既定 SKU 范围的高度会标记为未匹配。下单前请核实施工现场条件。',
      generatedBy: '由 ENMON 支座计算器生成',
      tiles600: '瓷砖（600×600）',
      pedestalsOutdoorFlooring: '支座与户外地面系统',
      unmatched: '未匹配',
    },
  },
}

const LanguageContext = createContext(null)

function detectLanguage() {
  if (typeof window === 'undefined') return 'en'

  const stored = window.localStorage.getItem(STORAGE_KEY)
  if (stored === 'en' || stored === 'zh') return stored

  const candidates = [...(navigator.languages || []), navigator.language].filter(Boolean)
  return candidates.some((value) => String(value).toLowerCase().startsWith('zh')) ? 'zh' : 'en'
}

function interpolate(template, params) {
  return Object.entries(params || {}).reduce(
    (text, [key, value]) => text.replace(new RegExp(`\\{${key}\\}`, 'g'), String(value)),
    template,
  )
}

function resolveTranslation(language, key) {
  const path = String(key || '').split('.')
  let value = translations[language]
  for (const part of path) value = value?.[part]
  return value
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(detectLanguage)

  useEffect(() => {
    if (typeof window === 'undefined') return
    window.localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key, params = {}) => {
      const raw = resolveTranslation(language, key) ?? resolveTranslation('en', key) ?? key
      return typeof raw === 'string' ? interpolate(raw, params) : raw
    },
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => useContext(LanguageContext)
